/** CDN assets from Stitch page1–page4 exports */
export const STITCH = {
  logo:
    'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/AAAGSURBVAMAQaTmdBT3_expires_30_days.png',
  logoAlt:
    'https://lh3.googleusercontent.com/aida/AP1WRLtveduqtiLF_2grDFfcE8URajrzq-3JOdCqYvuTGOVs4iTjVXLJz2VsT7jREp4mwVjELHa20Q5RVCxMMF1FYka_olvaGepGXImhNOsydicPkHInC9HW6QPD5uqrEO3pwELY1sUJG-CVcShQfXKjd92z-p2EiX_R-AuXtmbaKmnb2dg-t1KBsOhP1ffK3L_12_n4P5H9sF5M7MBhHTRK059I1QbuhsalkrxoNHM8FwetvBmLRTb-Wo6XotIS',
  search: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/p91uz6nw_expires_30_days.png',
  bell: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/u00jfw9i_expires_30_days.png',
  avatar: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/kb2ebi9l_expires_30_days.png',
  statVessels: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/9xl34dqj_expires_30_days.png',
  statHighRisk: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/q6v0lspe_expires_30_days.png',
  statAlerts: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/d638r4ex_expires_30_days.png',
  statInvestigations: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/sa0nav6o_expires_30_days.png',
  mapLayers: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/c9kdzho0_expires_30_days.png',
  mapLocate: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/eswx9g68_expires_30_days.png',
  mapRoute: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/er8mr5j1_expires_30_days.png',
  camera: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/otmzszvy_expires_30_days.png',
  closePanel: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/r0voxt84_expires_30_days.png',
  riskChart: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/ac1p9t7l_expires_30_days.png',
  investigateBtn: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/owh1v1pa_expires_30_days.png',
  watchlistBtn: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/u7favjz3_expires_30_days.png',
  alertInvestigate: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/ugosj3rz_expires_30_days.png',
  invStatActive: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/hvoclvi4_expires_30_days.png',
  invStatCompleted: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/ncuuedb9_expires_30_days.png',
  invStatPipeline: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/f4y3ua72_expires_30_days.png',
  invStatEscalations: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/u2gocglz_expires_30_days.png',
  invNewBtn: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/ngp4pp89_expires_30_days.png',
  invViewLive: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/dgudf332_expires_30_days.png',
  pipelineMonitoring: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/65rbz5tz_expires_30_days.png',
  pipelineInvestigation: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/xxhthl73_expires_30_days.png',
  pipelineCompliance: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/zw22hx1l_expires_30_days.png',
  pipelineEscalation: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/rqisqziz_expires_30_days.png',
  reportSearch: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/qg36d18v_expires_30_days.png',
  reportExport: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/0fsgdbxo_expires_30_days.png',
  reportFilter: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/t9w0dywi_expires_30_days.png',
  reportViewArrow: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/2n1rr5mc_expires_30_days.png',
  alertCriticalIcon: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/lm79i1tj_expires_30_days.png',
  alertMarkRead: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/12tR1oP5Zh/mc0pdskp_expires_30_days.png',
} as const;
